import java.util.Random;

public class Composition {
    private Random random = new Random();

    void randomNumber(){
        random.nextInt();
        //System.out.println("Random int generated by class Composition: " + (random.nextInt()));
    }
}
