import java.util.Random;

/**
 * Composition class creating a Random object.
 */
public class Composition {
    private Random random = new Random();

    /**
     * Randomizing an int.
     * Out commented parts can be re-included to give more clearity regarding the
     * execution of the method as prints to the console, if wanted.
     */
    void randomNumber(){
        //System.out.println("Random number generated by Composition: " +
        random.nextInt()
        //)
        ;
    }
}
