import java.util.Random;

/**
 * Class extending Random.
 */
public class Inheritance extends Random {

    /**
     * Randomizing an int. Out commented parts can be re-included to give more clearity regarding the
     * execution of the method as prints to the console, if wanted.
     */
    void randomNumber(){
        //System.out.println("Random number generated by Composition: " +
        super.nextInt()
        //)
        ;
    }
}
