import java.util.Random;

public class Inheritance extends Random {

    void randomNumber(){
        int random = super.nextInt();
        System.out.println("Random int generated by inheritance: " + random);
    }
}
